# Generated by Django 4.2 on 2023-04-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RecipeApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rcptable",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
