# Generated by Django 4.2 on 2023-04-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RecipeApp", "0002_rcptable_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rcptable",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
