# Generated by Django 4.2 on 2023-04-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RecipeApp", "0003_alter_rcptable_slug"),
    ]

    operations = []
